--------------------------------------------------------
--  Arquivo criado - quarta-feira-novembro-07-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONVENENTE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CONVENENTE" 
   (	"TPINSC" NUMBER(1,0), 
	"NRINSC" NUMBER(14,0), 
	"NOME" VARCHAR2(30 BYTE), 
	"BANCO" NUMBER(3,0), 
	"AG" NUMBER(5,0), 
	"AG_DV" VARCHAR2(1 BYTE), 
	"CONTA" NUMBER(12,0), 
	"CONTA_DV" VARCHAR2(1 BYTE), 
	"CONVENIO" VARCHAR2(20 BYTE), 
	"LOGRADOURO" VARCHAR2(30 BYTE), 
	"NUMERO" NUMBER(5,0), 
	"COMPLEMENTO" VARCHAR2(15 BYTE), 
	"CIDADE" VARCHAR2(20 BYTE), 
	"ESTADO" VARCHAR2(2 BYTE), 
	"CEP" NUMBER(5,0), 
	"CEP_COMP" VARCHAR2(3 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CONVENENTE
SET DEFINE OFF;
Insert into SYSTEM.CONVENENTE (TPINSC,NRINSC,NOME,BANCO,AG,AG_DV,CONTA,CONTA_DV,CONVENIO,LOGRADOURO,NUMERO,COMPLEMENTO,CIDADE,ESTADO,CEP,CEP_COMP) values ('2','12345678000195','XXX COMERCIO DE ALIMENTOS LTDA','5','9999','6','9999','6','0009999999999','AV DANIEL FLORIANO','2600',null,'JACAREI','SP','99999','999');
Insert into SYSTEM.CONVENENTE (TPINSC,NRINSC,NOME,BANCO,AG,AG_DV,CONTA,CONTA_DV,CONVENIO,LOGRADOURO,NUMERO,COMPLEMENTO,CIDADE,ESTADO,CEP,CEP_COMP) values ('2','12345','SSSIS','5','5',null,'7',null,'e546456',null,'5',null,null,null,'3',null);
Insert into SYSTEM.CONVENENTE (TPINSC,NRINSC,NOME,BANCO,AG,AG_DV,CONTA,CONTA_DV,CONVENIO,LOGRADOURO,NUMERO,COMPLEMENTO,CIDADE,ESTADO,CEP,CEP_COMP) values ('1','23456','shaft','5','3',null,'8',null,null,null,'4',null,null,null,'54',null);
